services:
  - type: web
    name: crypto-chat-backend
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /actuator/health
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: ENCRYPTION_MASTER_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: CRYPTO_GECKO_API_KEY
        sync: false
      - key: COINMARKETCAP_API_KEY
        sync: false
      - key: CRYPTOPANIC_API_KEY
        sync: false
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
